### ISSUE TITLE
MusicCast Stero Pair delay wrong

### ISSUE THREAD

**Issue by warthog9** [philippe44/LMS-to-Raop#10]
It's possible, with some MusicCast (read: Yamaha) to pair them into stereo left/right pairs.  When the speakers are by themselves, and you cast to them they sync perfectly with squeezebox.  However when you stereo pair them at the speakers, the delay changes and they are no longer properly in sync with LMS, seemingly always delayed behind a squeezebox radio used as the "test" point.  The delay seems to be consistent enough that two stereo paired sets of speakers seem to be in sync, but a single stereo paired set, and two non-paired speakers are not in sync.

I'm guessing that the left/right stereo pairing adds an additional delay into the raop (feels like an additional ~2 seconds) that isn't getting communicated back up to LMS?  Figured I'd open the bug and see if there was any suggested debugging to help try and narrow down the issue.

**Comment by philippe44** [comment]
The best is to use LMS's pairing option and do the pairing from there

**Comment by warthog9** [comment]
While I agree that's the more right way to do that, *IF* squeezebox is the only thing using those speakers, however there are clear use cases where that doesn't quite work:

- MusicCast's 5.1 channel setup where there's a number of speakers grouped into a single entity, usually for a theater system.  It would actually be very cumbersome to break that apart to make use of the squeezebox
- Cutting down on the number of devices one has to wade through in the squeezebox list since the L/R pair only shows up as a single device for grouped / paired speakers

I'm happy to do the debugging, or if it's an issue of getting you hardware I can likely donate you a pair if you'd like.

**Comment by philippe44** [comment]
I see - and no tweaking of LMS's synchronization delays helped? It should do the trick, it's what it's made for. I don't have enough Yamaha to create pairs and I have way too many speakers already at home, so I appreciate your offer, but I can't accept that.

**Comment by philippe44** [comment]
Closed for inactivity
