### ISSUE TITLE
Getting error: "Problem: Unable to play file type for : Main(Flac)" when playing Flac but works fine with ALAC files

### ISSUE THREAD

**Issue by Sedim** [philippe44/LMS-to-Raop#13]
![IMG_6636](https://user-images.githubusercontent.com/6205935/57182634-4cc64c00-6e6f-11e9-9506-5b10de6fd230.jpg)
[Logfile.log](https://github.com/philippe44/LMS-to-Raop/files/3144623/Logfile.log)

Trying to play Radio paradise or any Flac file but getting this error. Attached is the log file and pic of error. No problem playing ALAC

Hardware: Airport express Gen 2, Display is on Rpi

**Comment by Sedim** [comment]
Additional screen shot:
<img width="1109" alt="Screen Shot 2019-05-04 at 1 23 46 PM" src="https://user-images.githubusercontent.com/6205935/57182696-f9a0c900-6e6f-11e9-9b03-20492e63de10.png">

**Comment by philippe44** [comment]
FLAC shared library is probably not installed on your MAC, you'll see that in the bridge's log. You can either install it (sorry I'm not an OSX guy I don't remember how on top of my head, but it's easy) or you can use the -static version

**Comment by Sedim** [comment]
Solution: Just used the -static version. Works fine. You are the best as usual. Extraordinary software.
