### ISSUE TITLE
Apple TV TVOS 13 (Beta 5)

### ISSUE THREAD

**Issue by jpk8201** [philippe44/LMS-to-Raop#14]
I use the Airplay Bridge 0.4.16.1 on the Squeececenter with an Apple TV with TvOs 13, Beta 5 version. Since version 13 the streaming of music no longer works on the Apple TV. Connecting works, but the music is not played. On the Squeezecenter it looks like the music would be streamed. Do you have any idea what the problem might be? With version 12 everything still worked fine.

**Comment by philippe44** [comment]
Unfortunately no idea - I hope that Apple did not change again their protocol ...

**Comment by jpk8201** [comment]
Do you have an idea, what the message in the log file mean:

[19-08-13 18:45:45.3520] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Can't locate object method "new" via package "Plugins::RaopBridge::Async::HTTP" at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/RaopBridge/Pairing.pm line 57.
; fh=Slim::Web::HTTP::ClientConn=GLOB(0x564996784d30)

Server: Logitech Media Server Version: 7.9.2 - 1565679430 @ Tue Aug 13 09:16:03 CEST 2019
Plugin: v04.20.0

Thank you for your help

**Comment by philippe44** [comment]
It looks like you have updated something on your host os and the crypto libraries needed for pairing are not available anymore

**Comment by philippe44** [comment]
Close for inactivity
