### ISSUE TITLE
airplay volume scale doesn't allow loudness control at low volume.

### ISSUE THREAD

**Issue by jsarcand** [philippe44/LMS-to-Raop#15]
When configured to play through an appleTV 1st gen, the volume scale doesn't allow the adjustment of volume at low volume with the hardware volume control. 

It is as if the volume mapping should start at a value lower than -30.  Changing the mapping in the configuration file has an effect on the dynamic of the mapping.  when set to zero: no volume. When set to 1, there is already a vast amount of loudness, as if LMS was set to 20.  Software volume control do work as expected.
0 -------------------------100
-30 ----- -30--------------0

**Comment by philippe44** [comment]
Clsoed for inactivity (solved on LMS forum I think)
