### ISSUE TITLE
Help debugging raopbridge disconnections in LMS

### ISSUE THREAD

**Issue by fmalfatto** [philippe44/LMS-to-Raop#19]
Hi, I have my LMS on Raspberry, configured to wake up at 7:00 in the morning, and sending a webradio output to an Airplay Sony speaker. It works great for a lot of webradios, but one disconnects after a while. I tried to change timeouts and receive buffers, but nothing worked. Some days it works for more than 15 minutes, and somewhen crashes and then restarts before of the timeout.
How can I understand why? I have a very fast internet connection (130 Mbps and a fast local LAN), The speaker and LMS are cabled, no wifi problems between LMS and speakers.
Audio buffer is up to 10 sec, connection buffer is 50 sec, in both network and raopbridge

Thank you in advance

This is the log, cleaned from thousands of "Tick" lines (btw, how can I avoid such lines?):
` 
[rao.log](https://github.com/philippe44/LMS-to-Raop/files/5473959/rao.log)
`

**Comment by philippe44** [comment]
There is no log

**Comment by fmalfatto** [comment]
[rao.log](https://github.com/philippe44/LMS-to-Raop/files/5477374/rao.log)
Uploaded again ..

**Comment by philippe44** [comment]
So it's a few specific webradio that does not work? Do you have an URL?

**Comment by fmalfatto** [comment]
https://icestreaming.rai.it/2.mp3   or    http://icestreaming.rai.it/2.mp3
It works well on browsers and if called via LMS to Chromecast devices.
It looks as in the morning the webradio does not support many connections activated from wake-ups so I tried to modify buffers and timeouts without results. During the day it does not disconnect, or very rarely.

**Comment by philippe44** [comment]
Did you sort this out?

**Comment by fmalfatto** [comment]
No, I changed the local player from an airplay Sony to a google home and also in chromecast only  that one radio station is interrupted too. So I'm sure that is a problem involving the radio station server, not my players.
May close the issue. Thank you!

**Comment by philippe44** [comment]
Thanks for answering :-)
