### ISSUE TITLE
Cover art not emptied

### ISSUE THREAD

**Issue by thenktor** [philippe44/LMS-to-Raop#2]
Hi,

I'm using the bridge with an Apple TV 4k. Send LMS metadata to player is activated with cover art included. There is the following issue: If a song "X" with cover art is followed by a song "Y" without cover art then the cover art of song "X" remains on the display. Actually it should be emptied or replaced by some "no cover art" placeholder image.

**Comment by philippe44** [comment]
fixed in 0.3.3.0.4 (dev version)

**Comment by thenktor** [comment]
Thanks! 
Another issue that is related: When listening to an album the cover art actually stays the same but on Apple TV it is reloaded when songs change. This looks like some kind of display flickering.

**Comment by philippe44** [comment]
yes, everytime a new song starts, the coverart is gathererd again from LMS and updated, even if it's the same. I assume it's a quick flickering, no?

**Comment by thenktor** [comment]
Yes, screen is refreshed but it looks like flickering. Not a big deal, just not really slick. Maybe the cover art could be ckecked by the bridge (e.g. by md5sum) and only be sent if it differs from the previous one?

**Comment by philippe44** [comment]
There is already a hash but it's applied on the combined title and artwork, hence it is detected as changed. I'll see what I can do

**Comment by philippe44** [comment]
Should be in 0.3.3.0.6 - did not have time to test, your help would be appreciated :-)

**Comment by thenktor** [comment]
I've installed 0.3.3.0.6 and cover arts are emptied now. But part 2 of the feature request did not change: the cover art still is reloaded on song change.

Greetings

**Comment by philippe44** [comment]
oh well ... hopefully 0.3.3.0.7 should work in all conditions

**Comment by philippe44** [comment]
I did check direclty and even if artwork is not changed (and it is not) then my ATV4K flickers. It does the same when controlled from my iPhone, so I guess it happens when the title is changed. I'm 100% I'm not updating the artwork with this new version and logs confirms that

**Comment by thenktor** [comment]
Ok, so it‘s Apple‘s fault. But it was worth a try. Thanks!
