### ISSUE TITLE
German ö, ä, ü

### ISSUE THREAD

**Issue by fabian1512** [philippe44/LMS-to-Raop#22]
Hi,
I was trying to connect to my HomePod. It is in the room "Küche". Plugin shows up "Kuche" in the players list, but it can not be selected (checkmark jumps back after saving).
After changing the room to e.g. "Schlafzimmer" and generating the config, everything works fine. Changing the Room back to "Küche", the newly generated config does not show up "Küche". Instead it remains at "Schlafzimmer" and cannot be selected.

What went wrong? Could there be problems with the german "ö, ä, ü" ?
I am running the latest version 0.4.53.1

cheers

**Comment by philippe44** [comment]
It's probably because names with diacritics do not work when broadcasted with mDNS. For example, my test AirPort express replaces all of them with a dash. Maybe there is now something where they can be broadcasted but try to find our under what mDNS their appear

**Comment by philippe44** [comment]
Closed for inactivity
