### ISSUE TITLE
Metadata are one song late

### ISSUE THREAD

**Issue by ospring** [philippe44/LMS-to-Raop#9]
Hi, Using my Onkyo AV receiver as airplay receiver, When I play on a LMS group player, witch include the Airplay bridge player to my receiver, I have noticed that metadata displayed by my receiver are those of the previously played song (info, coverart and current/total timecode)....

**Comment by ospring** [comment]
More precisely, it occures at the end of the first song, displayed metadata is not refreshed with the next song and it stays to the current song (timecode go back to zero). aftewards, after the end of each song, it refresh with metadata of the previous one....

**Comment by ospring** [comment]
It is empirical : I noticed a delay between 2 grouped player : my AV receiver (AirPlay) and my computer (airplay via « air server » app). The player (not plug-in, in the sync submenu of lms player settings) audio delay settings seems to help correct the delay and the value of 1190 ms was needed to sync the audio (with the help of my hears ;) )
Maybe another setting can help me but I did not find it for the moment.

Note that when using iTunes client on PC and activate these two AirPlay target , the delay also exist and seems to be the same (but I did not mesure it and I prefer use the LMS system witch offer synchronized play)

**Comment by philippe44** [comment]
Oh I highly recommend you use squeezelite on your pc as well. Delay is stable and minimal and it’s a real SB client

**Comment by ospring** [comment]
It is not the pc airplay client who has the delay problem, it is my amplifier Onkyo TX-NR656 (AV receiver) witch is late by 1190 ms....

**Comment by philippe44** [comment]
hmmm ... that's very strange. Have you tried to sync it with another real SB device? I've never seen an AV receiver with such latency. I think that the PC forcing you to do that

**Comment by ospring** [comment]
Hi,

I have tested with squeezelite for Windows in sync with the bridge airplay player of my AV receiver and I have the same delay (with 0 as delay in the settings of LMS player)
Note that when playing with iTunes client to both airplay on Windows (Windows air server) and airplay of my receiver I Have this 1sec delay too...

Olivier

**Comment by philippe44** [comment]
Should be solved in latest version
